CONFIG_NAME: 'GBSN_test'

# ========== General options
device: 'cuda:0'
dataset_name: '22-train'
folder_sufix: '_None_1046'
# ======== changed to absolute paths 
doc_dict_folder_prefix: 'C:/Users/1/Desktop/karina_diploma/AuthorshipVerification-GraphBasedSiameseNetwork/data/PAN22_graphs/'
ds_list_folder_prefix: 'C:/Users/1/Desktop/karina_diploma/AuthorshipVerification-GraphBasedSiameseNetwork/data/PAN22_text_split/'
dest_folder_prefix: 'C:/Users/1/Desktop/karina_diploma/AuthorshipVerification-GraphBasedSiameseNetwork/test/test_output_siamese/test_command_line/'
epochs: 20 # ====== changed from 100 to 20
lim: 300 # ====== changed from 0 to 20
checkpoint_freq: 100
bm_free_epochs: 1
lr: 0.001
batch_size: 256
num_workers: 2 # ====== changed from 4 to 2

# ========== Datasets options
ds_op:
    exp_label: 'short'

# ========== Model options
exp_ops:
  #- model_class: SiameseNetwork
  - model_args:
        raw_components_list:
          - class: 'GBFeatures'
            args:
                conv_layers_num: 2
                conv_type: 'gnn.LEConv'
                h_ch: 64
                out_ch: 64
                pool_type: 'GlobalAttentionSelect'
                pool_att_ch: 32
                pool_att_layers: 2
                pool_ref: 'last'
        final_out_join: 'abs'
        final_out_layers_num: 2
        final_out_ch: 64
repeat_experiment: 1

# ========== Loss options
main_loss: 'soft_f1_loss'
