CONFIG_NAME: 'GBSN_test_med'

# ========== General options
device: 'cuda:0'
dataset_name: '20-small-bal'
folder_sufix: '_None_2000'
doc_dict_folder_prefix: 'data/PAN20_graphs/'
ds_list_folder_prefix: 'data/PAN20_text_split/'
dest_folder_prefix: 'test/test_output_siamese/test_command_line/'
epochs: 2
checkpoint_freq: 100
lim: 20
bm_free_epochs: 1
lr: 0.001
batch_size: 256
num_workers: 4

# ========== Datasets options
ds_op:
    exp_label: 'med'

# ========== Model options
exp_ops:
  #- model_class: SiameseNetwork
  - model_args:
        raw_components_list:
          - class: 'GBFeatures'
            args:
                conv_layers_num: 6
                conv_type: 'gnn.LEConv'
                h_ch: 64
                out_ch: 64
                pool_type: 'GlobalAttentionSelect'
                pool_att_ch: 32
                pool_att_layers: 4
                pool_ref: 'last'
        final_out_join: 'abs'
        final_out_layers_num: 4
        final_out_ch: 64
repeat_experiment: 1

# ========== Loss options
main_loss: 'BCE'
