CONFIG_NAME: 'GBSN_test_ensemble'

# En este ejemplo entrenamos un modelo GBSN Ensemble utilizando los pesos previamente
# entrenados de dos modelos short, un modelo med y las características lingüísticas

# ========== General options
device: 'cuda:0'
dataset_name: '22-train'
folder_sufix: '_None_1046'
doc_dict_folder_prefix: '../data/PAN22_graphs/'
ds_list_folder_prefix: '../data/PAN22_text_split/'
dest_folder_prefix: '../test/test_output_siamese/test_cl_ensemble/'
epochs: 2
checkpoint_freq: 100
lim:
bm_free_epochs: 1
lr: 0.001
batch_size: 256
num_workers: 4

# ========== Datasets options
# Por el momento, necesitamos anotar exactamente el típo de gráfica usado en cada
# componente para que funcione
ds_op:
    exp_label: 'ensemble'
    data_type_list:
      - 'short'
      - 'short'
      - 'med'
      - 'text_features'

# ========== Model options
exp_ops:
  #- model_class: SiameseNetwork
  - model_args:
        raw_components_list:
          - "../test/test_output_siamese/test_command_line/22-train_05100212/short_0-0/best_model_.pth"
          - "../test/test_output_siamese/test_command_line/22-train_05100222/short_0-0/best_model_.pth"
          - "../test/test_output_siamese/test_command_line/22-train_05101612/med_0-0/best_model_.pth"
          - class: 'TextFeatures'
            args:
                # Debe ser 191 si se quieren ocupar las características lingüisiticas
                # tal como las obtuvimos en PAN21
                num_text_features: 191
                text_feat_layers_num: 0
                h_ch: 64
                out_ch: 64
        final_out_join: 'abs'
        final_out_layers_num: 4
        final_out_ch: 64
repeat_experiment: 1

# ========== Loss options
main_loss: 'BCE'
